schema_version: 20180708
name: string-reverse
version: 0.0.2
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.87
run_image: fnproject/fn-java-fdk:jre11-1.0.87
cmd: com.example.fn.StringReverse::reverse
triggers:
- name: string-reverse
  type: http
  source: /string-reverse
