FROM openjdk:11-jre-slim
COPY target/runtime-*.jar target/dependency/*.jar /function/runtime/
COPY src/main/c/libfnunixsocket.so /function/runtime/lib/

RUN ["/usr/local/openjdk-11/bin/java", "-Xshare:dump"]

RUN addgroup --system --gid 1000 fn && adduser --uid 1000 --gid 1000 fn

# The UseExeperimentalVMOptions, UseCGroupMemoryLimitForHeap and MaxRAMFraction options that were used in the JDK 9 builds are
# no longer supported in JDK 11 - so these have been removed. We now rely on the built-in ContainerSupport option that Linux JDKs
# use to configure themselves when detecting they are running in a container.
#
# SerialGC is used here as it's likely that we'll be running many JVMs on the same host machine and it's also likely
# that the number of JVMs will outnumber the number of available processors.
#
ENTRYPOINT [ "/usr/local/openjdk-11/bin/java", "-XX:-UsePerfData", "-XX:+UseSerialGC", "-Xshare:on", \
     "-Djava.awt.headless=true" , \
     "-Djava.library.path=/function/runtime/lib", \
     "-cp", "/function/app/*:/function/runtime/*", \
     "com.fnproject.fn.runtime.EntryPoint" ]
