version: 2
jobs:
  build:
    working_directory: ~/fn-java-fdk
    machine:
      image: ubuntu-1604:202101-01
    environment:
      # store_artifacts doesn't shell substitute so the variable
      # definitions are duplicated in those steps too.
      FDK_ARTIFACT_DIR: /tmp/artifacts/fdk
      TEST_ARTIFACT_DIR: /tmp/artifacts/tests
      REPOSITORY_LOCATION: /tmp/staging_repo
    steps:
      - checkout
      - run:
         name: Update Docker to latest
         command: ./.circleci/install-docker.sh
      - run:
         name: GPG version check
         command: gpg  --version
      - run:
         name: Import GPG Owner Trust
         command: echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
      - run:
         name: Import GPG key
         command: echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
      - run:
          name: Install fn binary (as it is needed for the integration tests)
          command: ./.circleci/install-fn.sh
      - run:
          name: Workaround for https://issues.apache.org/jira/browse/SUREFIRE-1588
          command: ./.circleci/fix-java-for-surefire.sh
      - run:
          name: Install junit-merge
          command: npm install -g junit-merge
      - run:
           name: Set release to latest branch version
           command: |
               git checkout origin/${CIRCLE_BRANCH} release.version
               echo next release version is $(cat release.version)
      - run:
           name: Determine the release version
           command: ./.circleci/update-versions.sh
      - deploy:
          name: Release new version
          command: |
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              ./.circleci/release.sh

