version: 2
jobs:
  build:
    working_directory: ~/fn-java-fdk
    machine:
      java:
        version: oraclejdk8
    environment:
      ARTIFACT_DIR: /tmp/artifacts
      STAGING_DIR: /tmp/staging-repository
    steps:
      - checkout
      - restore_cache:
          key: mvn-cache

      - run:
          name: Build, Test and Package.
          command: mvn package
      - store_test_results:
          path: runtime/target/surefire-reports
      - store_test_results:
          path: testing/target/surefire-reports
      - run:
          name: Copy FDK artifacts to upload folder
          command: |
            mkdir $ARTIFACT_DIR
            cp api/target/*.jar $ARTIFACT_DIR
            cp runtime/target/*.jar $ARTIFACT_DIR
      - store_artifacts:
          name: Upload FDK artifacts
          path: $ARTIFACT_DIR
      - run:
          name: Perform a local staging deploy of the maven artifacts
          command: |
            mkdir -p "$STAGING_DIR"
            mvn deploy -DskipTests -DaltDeploymentRepository=localStagingDir::default::file://"$STAGING_DIR"

      - run:
         name: Update Docker to latest
         command: ./.circleci/install-docker.sh
      - run:
         name: Login to Docker
         command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build fn-java-fdk Docker image
          command: |
            cd runtime
            docker build -t fnproject/fn-java-fdk .

      - run:
          name: Install fn binary (as it is needed for the integration tests)
          command: ./.circleci/install-fn.sh
      - run:
          name: Run integration tests
          command: REPOSITORY_LOCATION="$STAGING_DIR" ./integration-tests/run-local.sh
          timeout: 1200

      - deploy:
          name: Push to maven repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mvn -s ./settings-deploy.xml \
                  -DskipTests \
                  -DaltDeploymentRepository="bmcs-faas-snapshot-repo::default::https://swiftobjectstorage.us-phoenix-1.oraclecloud.com/v1/opc0002/mvnrepo/snapshots" \
                  -Dbmcs-faas-snapshot-repo.username="$MVN_SNAPSHOT_USER" \
                  -Dbmcs-faas-snapshot-repo.password="$MVN_SNAPSHOT_PASSWORD" \
                  -DdeployAtEnd=true \
                  deploy
            fi
      - deploy:
          name: Deploy fn-java-fdk Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push fnproject/fn-java-fdk
            fi

      - save_cache:
          paths:
            - ~/.m2
          key: mvn-cache
