/*
 * Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pipeline {
    agent any
    parameters {
        string(name: 'IMAGE', defaultValue: 'registry.oracledx.com/skeppare/functions-service:latest', description: 'Which image to use (full repository:tag, e.g. fnproject/fnserver:latest)')
        string(name: 'SOURCE_REPO', defaultValue: 'git@github.com:fnproject/fn.git', description: 'Which git repo to use to build the CLI tool')
        string(name: 'SOURCE_BRANCH', defaultValue: 'master', description: 'Which git repo branch to use to build the CLI tool')
    }
    stages {
        stage('Update functions deployment image') {
            steps {
                sh ". /home/mjg/proxy ; kubectl set image deployment/fn-service fn-service=${params.IMAGE}"
            }
        }
        stage('Update fn cli tool') {
            steps {
                dir('cli') {
                    git url: "${params.SOURCE_REPO}", branch: "${params.SOURCE_BRANCH}"
                    sh 'docker run --rm -v "$PWD":/go/src/github.com/fnproject/fn -v /usr/local/bin:/go/bin -w /go/src/github.com/fnproject/fn/cli golang:1.8 go build -o /go/bin/fn'
                }
            }
        }
    }
}
