#
# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM alpine:latest

WORKDIR /build
COPY src src
COPY pom.xml .
COPY func.init.yaml .
COPY Dockerfile.build Dockerfile

RUN echo $'#!/bin/sh\n\
if [ -n ${FN_FUNCTION_NAME} ]\n\
    then\n\
    JAVA_NAME=$(echo ${FN_FUNCTION_NAME:0:1} | tr "[:lower:]" "[:upper:]")${FN_FUNCTION_NAME:1}\n\
    sed -i -e "s|<artifactId>hello</artifactId>|<artifactId>${FN_FUNCTION_NAME}</artifactId>|" pom.xml\n\
    sed -i -e "s|com.example.fn.HelloFunction|com.example.fn.${JAVA_NAME}|" Dockerfile\n\
    sed -i -e "s|com.example.fn.HelloFunction|com.example.fn.${JAVA_NAME}|" src/main/resources/META-INF/native-image/fnfunction/reflect-config.json\n\
    sed -i -e "s|HelloFunction|${JAVA_NAME}|" src/main/java/com/example/fn/HelloFunction.java\n\
    mv src/main/java/com/example/fn/HelloFunction.java "src/main/java/com/example/fn/${JAVA_NAME}.java"\n\
    sed -i -e "s|HelloFunction|${JAVA_NAME}|" src/test/java/com/example/fn/HelloFunctionTest.java\n\
    mv src/test/java/com/example/fn/HelloFunctionTest.java "src/test/java/com/example/fn/${JAVA_NAME}Test.java"\n\
fi\n\
tar c src pom.xml func.init.yaml Dockerfile\n' > build_init_image.sh \
    && chmod 755 build_init_image.sh

CMD ["./build_init_image.sh"]
