FROM debian:buster-slim as build
LABEL maintainer="tomas.zezula@oracle.com"

RUN set -x \
    && apt-get -y update \
    && apt-get -y install gcc g++ git make python zlib1g-dev wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

RUN set -x \
    && git clone --depth 1 https://github.com/graalvm/mx.git \
    && wget -q --output-document jvmcijdk.tar.gz https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-20.0-b02/labsjdk-ce-11.0.6+9-jvmci-20.0-b02-linux-amd64.tar.gz \
    && mkdir jvmcijdk11 \
    && tar -xz --strip 1 -f jvmcijdk.tar.gz -C /build/jvmcijdk11 \
    && rm jvmcijdk.tar.gz

RUN git clone --single-branch https://github.com/oracle/graal.git --branch release/graal-vm/20.0
WORKDIR /build/graal/vm
RUN export JAVA_HOME=/build/jvmcijdk11 \
    && /build/mx/mx --dy /substratevm --force-bash-launchers=true --disable-polyglot --skip-libraries=true build

WORKDIR /build/graal/vm/latest_graalvm
RUN LONG_NAME=$(ls) \
    && SHORT_NAME=graalvm \
    && mv $LONG_NAME $SHORT_NAME

FROM debian:stretch-slim as final
LABEL maintainer="tomas.zezula@oracle.com"

RUN set -x \
    && apt-get -y update \
    && apt-get -y install gcc zlib1g-dev

COPY --from=build /build/graal/vm/latest_graalvm/graalvm /usr/local/graalvm
COPY src/main/c/libfnunixsocket.so /function/runtime/lib/


ENV GRAALVM_HOME=/usr/local/graalvm
WORKDIR /function
