#
# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This is run once, at cluster creation time. It creates and sets up the
# components of the flow service, and assumes that the functions service
# is already provisioned from:
#
#     https://gitlab-odx.oracle.com/odx/functions-service/tree/master/scripts/fn-service.yml
#
# The created service has persistent storage to a single-stage MySQL database.
#
# Updates are done by:
#
#    $ kubectl set image deployment/completer-service completer-service=NEW_IMAGE_FULL_PATH
#
---
apiVersion: v1
kind: Secret
metadata:
  name: completer-mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: YWtrYQ==
  MYSQL_USER: cXNSaFVNWVo1NXFDdWg4T29lbVo0c2hxQndEYzNo
  MYSQL_PASSWORD: eXF2cEhEUFliU3lyWU9VdHVsb08zQThXTWtKVGFKdmIzTnQ3dFVaZkE4NHlFWnBueXlpUEF3
  MYSQL_ROOT_PASSWORD: N1ZSRWlUSFRXMDlQbnhETzRIQUVQWkxhREEwSHZVQ1pBNWZuVDl3akdEd3ExSk5yRmE3TUhn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completer-persistence-schema-file
data:
  schema-file.sql: |
    USE akka;
    CREATE TABLE IF NOT EXISTS journal (
      ordering SERIAL,
      persistence_id VARCHAR(255) NOT NULL,
      sequence_number BIGINT NOT NULL,
      deleted BOOLEAN DEFAULT FALSE,
      tags VARCHAR(255) DEFAULT NULL,
      message BLOB NOT NULL,
      PRIMARY KEY(persistence_id, sequence_number)
    );
    CREATE TABLE IF NOT EXISTS snapshot (
      persistence_id VARCHAR(255) NOT NULL,
      sequence_number BIGINT NOT NULL,
      created BIGINT NOT NULL,
      snapshot BLOB NOT NULL,
      PRIMARY KEY (persistence_id, sequence_number)
    );

---
apiVersion: v1
kind: Service
metadata:
  name: completer-persistence-mysql
  labels:
    app: completer-mysql
    role: datastore
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: completer-mysql
    role: datastore
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: completer-persistence-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: completer-mysql
        role: datastore
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: completer-mysql
        image: mysql:5.7
        imagePullPolicy: Always
        args:
          - "--max-connections=500"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_DATABASE
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: schema-file
      volumes:
      - name: schema-file
        configMap:
          name: completer-persistence-schema-file
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: completer-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: completer-service
    spec:
      containers:
      - name: completer-service
        image: registry.oracledx.com/skeppare/cloud-completer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http-server
        env:
        - name: CONFIG_RESOURCE
          value: prod.conf
        - name: MYSQL_HOST
          value: completer-persistence-mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: completer-mysql-secret
              key: MYSQL_DATABASE
        - name: FN_HOST
          value: fn-service
        - name: FN_PORT
          value: "8080"
      imagePullSecrets:
        - name: odx-registry-secret
---
kind: Service
apiVersion: v1
metadata:
  name: completer-service
  labels:
    app: completer-service
spec:
  clusterIP: 10.32.0.66
  ports:
  - port: 8081
    targetPort: http-server
    nodePort: 31750
  selector:
    app: completer-service
  type: NodePort
