FROM maven:3-jdk-9-slim

ADD pom.xml /tmp/cache-deps/pom.xml
ADD cache-deps.sh /tmp/cache-deps/cache-deps.sh
ADD src /tmp/cache-deps/src
ADD settings.xml /tmp/settings.xml

RUN /tmp/cache-deps/cache-deps.sh
